### Sistema de Análise de Irrigação Agrícola

In [1]:
# Importação das bibliotecas

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from scipy.stats import shapiro, kstest, probplot
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 
from statsmodels.graphics.gofplots import qqplot

Carga dos dados

In [5]:
# Abrir o dataset
df_irrigacao = pd.read_csv('./datasets/dados_de_irrigacao.csv')

In [6]:
# Checar estrutura do Dataset
df_irrigacao.info()

<class 'pandas.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Horas de Irrigação        299 non-null    int64
 1   Área Irrigada             299 non-null    int64
 2   Área Irrigada por Ângulo  299 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 7.1 KB

In [7]:
# Visualizar topo do dataset
df_irrigacao.head()

   Horas de Irrigação  Área Irrigada  Área Irrigada por Ângulo
0                   1            100                 66.666667
1                   2            200                133.333333
2                   3            300                200.000000
3                   4            400                266.666667
4                   5            500                333.333333

In [8]:
# Visualizar final do dataset
df_irrigacao.tail()

     Horas de Irrigação  Área Irrigada  Área Irrigada por Ângulo
294                 295          29500              19666.666667
295                 296          29600              19733.333333
296                 297          29700              19800.000000
297                 298          29800              19866.666667
298                 299          29900              19933.333333